// <auto-generated />
namespace revSpeed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _29032019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_29032019));
        
        string IMigrationMetadata.Id
        {
            get { return "201903291601308_29032019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
